@startuml
skinparam backgroundColor transparent
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam rectangle {
  BackgroundColor #FDFDFD
  BorderColor #333333
  roundCorner 8
}
top to bottom direction
rectangle "Ui" as ui
rectangle "Logic" as logic
rectangle "Model" as model
rectangle "Storage" as storage
ui --> logic
logic --> model
logic --> storage
storage --> model
legend bottom
  arrow: <b>depends on</b>
endlegend
@enduml
