@startuml
skinparam classAttributeIconSize 0
skinparam shadowing false
hide circle
hide empty members
class a as "__adam:Student__"
class e as "__eve:Student__"
class h as "__h1:Hall__"
class d1 as "__history:Degree__"
class d2 as "__english:Degree__"
a -- d1
a -right- h
e -left- h
e -- "major" d2
@enduml
