@startuml
skinparam classAttributeIconSize 0
skinparam roundCorner 0
skinparam shadowing false
hide circle
hide empty members
class a as "<u>adam:Student</u>"
class e as "<u>eve:Student</u>"
class h as "<u>h1:Hall</u>"
class d1 as "<u>history:Degree</u>"
class d2 as "<u>english:Degree</u>"
a -- d1
a -right- h
e -left- h
e -- "major" d2
@enduml
