@startuml
skinparam classAttributeIconSize 0
skinparam backgroundcolor transparent
skinparam shadowing false
hide circle
class Logic <<Singleton>> {
{static} <b><color:red>-</color>theOne</b>:  Logic
<b><color:red>-</color></b>Logic()
<color:red>{static} +<b>getInstance()</b>: Logic</color>
}
@enduml