@startuml
skinparam classAttributeIconSize 0
skinparam backgroundcolor transparent
skinparam shadowing false
hide circle
class Person {
{static} <b><color:red>getMaxAge():  int</color></b>
setAge(int): void
}
@enduml
