@startuml
skinparam Shadowing false
hide footbox
participant "m:Main" as Main
participant "<b><color:red><<class>></color></b>\nPerson" as PersonClass
participant "p:Person" as Person

Main -> PersonClass ++ : getMaxAge()
return max age
Main -> Person ++ : setAge(5)
return
@enduml
